### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Quezler**
Add a troubleshooting clause that cost me 5 minutes of my life to figure out.

### CODE REVIEW

**Comment by rhyek** [comment]
Hm, actually, I ran into a similar issue when developing the component and supposedly this line addresses that: https://github.com/rhyek/vue-bootstrap-toggle/blob/8db0064e89e84cf47ea524dc4ca6ae2c8198bb6c/src/index.vue#L6

Do you know if you were including your app.js before or after bootstrap-toggle.js?

**Comment by Quezler** [comment]
I tried before and after.

Before did not work, since jQuery is inside the app.js
After did not work, since then bootstrapToggle would be undefine.

Currently i cache my app.js using [basket.js](https://github.com/addyosmani/basket.js), and that sorta fixed it.

But since then 2 instances were listening to the same dom elements, they would always toggle twice, resulting in nothing.

**Comment by Quezler** [comment]
Oh, i forgot to add:

When i had bootstrapToggle 'under' the basket.js loading the app.js, it failed because it needed jQuery.

And since basket.js loads them in order if both are loaded using basket, yours would load first, and then the official one.

Im pretty sure you get the same results if you load app.js before bootstrapToggle, basket or not.

**Comment by rhyek** [comment]
I have to run some tests. This really shouldn't be happening. Would you mind creating an issue?

**Comment by rhyek** [comment]
I'll merge this for now and test later. I'm pretty sure it has something to do with how `bootstrap-toggle` is checking for duplicate initialization.

**Comment by Quezler** [comment]
Yay `Contributor` tag 😄

**Pull request merged**
